### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by Bosek** [farshield/wingspanstats#2]
Can you make JSON output for results? I'd like to make a simple website(react) and host it on my dedicated machine, so we can have data almost realtime(max 1 hour delay) :)

**Comment by Bosek** [comment]
I've made own fork and added it. I guess I can close this one.

**Comment by farshield** [comment]
When I wrote this app I didn't have real-time data processing in mind, especially in the way on how I retrieve data from Zkill (didn't want to hammer Zkill with requests). I plan to do a website myself in the future, but not real-time. You are of course welcome to do a real-time statistic if you want. Ask if you need anything o7
